{
      "*** Testing all simple operators ***";
      "types";
      double d1 = 123.4;
      double d2 = 1.234e2;
      int a, b, c;
      char chtab = '\t';
      char chnorm = 'A';
      boolean A = true;
      boolean B = false;
      d.valor = true;
      int[] e = {1 , 2, 3};
      e = new int[4];
      e[0] = 0;
      ;
      "arithmetic";
      c = a + b;
      c = a - b;
      c = a * b;
      c = a / b;
      c = a % b;
      "coucou " + " souris" + 2;
      ;
      "unary";
      a++;
      b--;
      ++a;
      --b;
      ;
      "Bitwise";
      c = a & b;
      c = a | b;
      c = a ^ b;
      c = ~a;
      c = a << 2;
      c = a >> 2;
      c = a >>> 2;
      ;
      "booleans";
      A = A || B;
      A = A && B;
      A = !A;
      A = A ^ B;
      ;
      "assignments";
      a += b;
      a -= b;
      a *= b;
      a /= b;
      a %= b;
      a &= b;
      a |= b;
      a ^= b;
      a >>= b;
      a <<= b;
      a >>>= b;
      ;
      "conditional assignment";
      a = a < b ? 2 : c; 
      ;
      "*****************";
      "ERROR EXPRESSIONS";
      a =*true;
      a =/true;
      a =%true;
      a =&true;
      a =|true;
      a=true!;
      a=10~;
}
