(* Add JavaRuntimeExceptions *)
exception ArithmeticException
exception ArrayIndexOutOfBoundsException
exception ArrayStoreException
exception ClassCastException
exception IllegalArgumentException
exception IllegalMonitorStateException
exception IllegalStateException
exception IllegalThreadStateException
exception IndexOutOfBoundsException
exception NegativeArraySizeException
exception NullPointerException
exception NumberFormatException
exception SecurityException
exception StringIndexOutOfBounds
exception UnsupportedOperationException
exception ClassNotFoundException
exception CloneNotSupportedException
exception IllegalAccessException
exception InstantiationException
exception InterruptedException
exception NoSuchFieldException
exception NoSuchMethodException
exception Exception of string 